### ISSUE TITLE
Fix: rollback to sl4j 1.7.x for better compatibility

### ISSUE THREAD

**Issue by vtintillier** [SAP/btp-environment-variable-access#111]
Hello,

as already discussed in related project https://github.com/SAP/cloud-security-xsuaa-integration/issues/1036, it would be better if this project would rollback to slf4j 1.7.x instead of using 2.0.x.

The issue with slf4j 2.0 is that it requires using a newer version (1.3) of logback, whereas slf4j 1.7 is compatible with both logback 1.2 and 1.3. Especially Spring Boot 2.x comes with slf4j 1.7 and logback 1.2.

At the moment, we have to manage `com.sap.cloud.environment.servicebinding:*` dependencies explicitely in our maven poms to exclude its transitive dependency on slf4j. For now things work only because this project does not use the new slf4j 2.0 API, but would it start using it, it would no longer work.

That's why the safer way is to just rollback slf4j-api to 1.7.36, and to prevent Dependabot to update this dependency.

I can do a PR for this.

Thanks
Vivien

**Comment by liga-oz** [comment]
https://github.com/SAP/cloud-security-xsuaa-integration/issues/1036#issuecomment-1443699891

**Comment by newtork** [comment]
Please correct me,

`org.slf4j slf4j-api` has no transitive dependency to _logback_, right?

**Comment by vtintillier** [comment]
> Please correct me:
> 
> * `org.slf4j:slf4j-api` has no transitive dependency to _logback_, right?

correct, it is the other way around

> * the dependency version for this **API** artifact should hopefully be downwards compatible (not checked)

it is, until someone uses new API from slf4j-api 2.0 (accidentally or on purpose). And if nobody uses such new API, then it is the same for this project to just use slf4j 1.7, especially as it removes unnecessary work on the client side.

I discussed this with @liga-oz in https://github.com/SAP/cloud-security-xsuaa-integration/issues/1036 as mentioned already, and now that the issue is fixed in https://github.com/SAP/cloud-security-xsuaa-integration, the issue is now with this project. So doing the same fix would be great 😃

**Comment by vtintillier** [comment]
> I don't see that to be an issue caused by this library. Can you please (privately) link the POM file, where the exclusion is necessary?

I can do a sample project similar to the one I did for https://github.com/SAP/cloud-security-xsuaa-integration/issues/1036, but if you could first sync up with @liga-oz , it could avoid doing the same again 😃

**Comment by newtork** [comment]
I'll check back with Liga.
Feel free to create a PR, if you want.

Right now I feel some strong reservations about a dependency downgrade for a product update :)

**Comment by liga-oz** [comment]
@newtork as long as you don't use fluent-API from slf4j-api 2.x, we are safe and it won't break security libs.

**Comment by vtintillier** [comment]
I created similar sample repository: https://github.com/vtintillier/btp-environment-variable-access-111

You can clone or open in a codespace workspace, and run `mvn validate`. It will fail with

```
[INFO] --- enforcer:3.1.0:enforce (default) @ demo ---
[ERROR] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.slf4j:slf4j-api:1.7.36 paths to dependency are:
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.sap.cloud.security:java-security:2.13.6
    +-com.sap.cloud.security:java-api:2.13.6
      +-org.slf4j:slf4j-api:1.7.36 (managed) <-- org.slf4j:slf4j-api:1.7.36
and
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.sap.cloud.security:java-security:2.13.6
    +-com.sap.cloud.security.xsuaa:token-client:2.13.6
      +-org.slf4j:slf4j-api:1.7.36 (managed) <-- org.slf4j:slf4j-api:1.7.36
and
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.sap.cloud.security:java-security:2.13.6
    +-com.sap.cloud.security:env:2.13.6
      +-com.sap.cloud.environment.servicebinding:java-sap-vcap-services:0.5.2
        +-org.slf4j:slf4j-api:1.7.36 (managed) <-- org.slf4j:slf4j-api:2.0.5
and
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.sap.cloud.security:java-security:2.13.6
    +-com.sap.cloud.security:env:2.13.6
      +-com.sap.cloud.environment.servicebinding:java-sap-service-operator:0.5.2
        +-org.slf4j:slf4j-api:1.7.36 (managed) <-- org.slf4j:slf4j-api:2.0.5
and
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.sap.cloud.security:java-security:2.13.6
    +-com.sap.cloud.security:env:2.13.6
      +-com.sap.cloud.environment.servicebinding.api:java-access-api:0.5.2
        +-org.slf4j:slf4j-api:1.7.36 (managed) <-- org.slf4j:slf4j-api:2.0.5
and
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.sap.cloud.security:java-security:2.13.6
    +-com.sap.cloud.security.xsuaa:token-client:2.13.6
      +-ch.qos.logback:logback-classic:1.2.11 (managed) <-- ch.qos.logback:logback-classic:1.2.11
        +-org.slf4j:slf4j-api:1.7.36 (managed) <-- org.slf4j:slf4j-api:1.7.32
and
+-com.example:demo:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-security:2.7.9
    +-org.springframework.boot:spring-boot-starter:2.7.9 (managed) <-- org.springframework.boot:spring-boot-starter:2.7.9
      +-org.springframework.boot:spring-boot-starter-logging:2.7.9 (managed) <-- org.springframework.boot:spring-boot-starter-logging:2.7.9
        +-org.apache.logging.log4j:log4j-to-slf4j:2.17.2 (managed) <-- org.apache.logging.log4j:log4j-to-slf4j:2.17.2
          +-org.slf4j:slf4j-api:1.7.36 (managed) <-- org.slf4j:slf4j-api:1.7.35
and
+-com.example:demo:0.0.1-SNAPSHOT
  +-org.springframework.boot:spring-boot-starter-security:2.7.9
    +-org.springframework.boot:spring-boot-starter:2.7.9 (managed) <-- org.springframework.boot:spring-boot-starter:2.7.9
      +-org.springframework.boot:spring-boot-starter-logging:2.7.9 (managed) <-- org.springframework.boot:spring-boot-starter-logging:2.7.9
        +-org.slf4j:jul-to-slf4j:1.7.36 (managed) <-- org.slf4j:jul-to-slf4j:1.7.36
          +-org.slf4j:slf4j-api:1.7.36 (managed) <-- org.slf4j:slf4j-api:1.7.36
```

**Comment by vtintillier** [comment]
> Feel free to create a PR, if you want.

Done

**Comment by newtork** [comment]
Hi @vtintillier,

I tried to get the whole picture. Please correct me if I'm wrong:
* Your application depends on Spring Boot version `2.7.9` ([2023-02-23](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent/2.7.9)) and SLF4J API version `1.7.36` ([2022-02-08](https://mvnrepository.com/artifact/org.slf4j/slf4j-api/1.7.36))
* Your application depends on **this project** transitively with SLF4J API version `2.0.6` ([2022-12-13](https://mvnrepository.com/artifact/org.slf4j/slf4j-api/2.0.6)) https://github.com/SAP/btp-environment-variable-access/blob/9a2672ab503cf1b54f407edd16b55cbeb7780e40/bom/pom.xml#L53
* Your application uses Maven plugin `maven-enforcer-plugin` with rule [requireUpperBoundDeps](https://maven.apache.org/enforcer/enforcer-rules/requireUpperBoundDeps.html):
  > This rule requires that the version for each dependency resolved during a build, is equal to or higher than all transitive dependency declarations



With that your own build process fails, since the plugin finds transitive dependencies that are newer than version chosen with highest priority, e.g. `org.slf4j:slf4j-api:1.7.36 (active) < org.slf4j:slf4j-api:2.0.6 (overruled)`.

That means, even **if** we decide to downgrade SLF4J-API, then the very next dependency update (e.g. `org.json:json`) will result in the same error for you. In order to keep you happy, we would need to forever stick to transitives dependencies dictated by Spring Boot `2.7.9`. This is not future-proof. Of course, for this project, we could explore other options, like completely removing SLF4J (and `org.json:json`) from our project. But none of it seems viable to me right now.

---

I see your options as:

* Disable the plugin. (Not good)
* Disable the failing rule. (Unfortunate)
  ```diff
  - <requireUpperBoundDeps/>
  ```
* Customize the rule. (**Recommended**)
  ```diff
  - <requireUpperBoundDeps/>
  + <requireUpperBoundDeps>
  +   <excludes>
  +     <exclude>org.slf4j:slf4j-api</exclude>
  +   </excludes>
  + </requireUpperBoundDeps>
* Enforce newer version (not ideal)
  ```diff
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.6</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  ```
  or 
  ```diff
    <dependencies>
  +     <dependency>
  +       <groupId>org.slf4j</groupId>
  +       <artifactId>slf4j-api</artifactId>
  +       <version>2.0.6</version>
  +     </dependency>
  ...
  ```
  This will result in warning messages like:
  ```
  SLF4J: No SLF4J providers were found.
  SLF4J: Defaulting to no-operation (NOP) logger implementation
  SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
  SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
  ```
* Add exclusion (Not ideal)
  ```diff
  <dependency>
    <groupId>com.sap.cloud.security</groupId>
    <artifactId>java-security</artifactId>
    <version>2.13.6</version>
  + <exclusions>
  +     <exclusion>
  +    <groupId>org.slf4j</groupId>
  +    <artifactId>slf4j-api</artifactId>
  +    </exclusion>
  + </exclusions>
  </dependency>
  ```

Kind regards
Alexander

**Comment by vtintillier** [comment]
Hi @newtork 

> That means, even **if** we decide to downgrade SLF4J-API, then the very next dependency update (e.g. `org.json:json`) will result in the same error for you. In order to keep you happy, we would need to forever stick to transitives dependencies dictated by Spring Boot `2.7.9`. This is not future-proof. Of course, for this project, we could explore other options, like completely removing SLF4J (and `org.json:json`) from our project. But none of it seems viable to me right now.

no, that's not the same. We don't restrict ourselves to versions defined in Spring Boot. If you'd use a newer version of `org.json`, then we would just configure our dependencies to use that newer `org.json` version, if possible of course. If you start using a version of `org.json` that breaks compatibility, or is incompatible with another dependency, or is compiled with Java 19, yes sure, we would have no choice but excluding that dependency.

The difference here is that

1. you just don't _need_ slf4j-api 2.0. You just happened to have merged automated Dependabot PRs. (which is a good tool, but should be used more carefully with libraries than applications)
2. slf4j-api 2.0 requires your client to change their existing logging framework (logback upgrade for example), whereas slf4j-api 1.7 in your library would be compatible with both applications using old and new logback/slf4j versions.

I just ask if you can use the version that is the most compatible instead of the least compatible.

> Customize the rule. (Recommended)

the whole point of this rule is to be sure which version of dependency is used in the end. If we ignore it, we could introduce a new dependency that _really_ needs slf4j 2.0, and it would break at runtime.

Thanks
Vivien

**Comment by newtork** [comment]
Hi @vtintillier,

> you just don't need slf4j-api 2.0. You just happened to have merged automated Dependabot PRs.

That's right. I won't be arguing that.

> slf4j-api 2.0 requires your client to change their existing logging framework

That's confusing to me: our project does not force your application to use SLF4J API `2.0.6`. The opposite is the case here, with `1.7.36` taking precedence.

> the whole point of this [Maven plugin] rule is to be sure which version of dependency is used in the end.

Who has to "be sure"? The developer? The Maven runtime? For me the `dependency-tree` gives a conflict free dependency resolution. We are arguing on behalf of a 3rd party plugin and rule right now :)

I think with your intention the only proper solution with the *current* releases would be to add an exclusion to the affected dependency, here `java-security`, i.e. the last option [in my list.](https://github.com/SAP/btp-environment-variable-access/issues/111#issuecomment-1453740142)

Kind regards
Alenxader

**Comment by newtork** [comment]
Before drawing conclusions, we could wait until Monday to hear the opinion of top-contributor @Johannes-Schneider. Maybe he has a different risk/value assessment 👍

**Comment by jjtang1985** [comment]
Hi @vtintillier 

There are 3 major concerns from my side:
- Why as a small lib (BTP service binding), I have to be bound to big framework like Spring Boot?
- From your point of view, as a library developer, I cannot upgrade **any** dependencies in the future, because I have to make Spring Boot or other framework happy. Therefore, keeping old version will be safe. 
However, keep using old libraries also brings additional risks of vulnerabilities. In addition, my scanning tools like blackduck will also tell me, my libraries are outdated. Therefore, as long as application developers can add additional configurations to solve such maven enforce plugin issue (as Alex said, with `exclusion`, runtime has no issues), I dont see better solution.
- Rolling back to slf4j version 1 will be a breaking change.

Best regards,
Junjie

**Comment by vtintillier** [comment]
Hi @jjtang1985 

> * Why as a small lib (BTP service binding), I have to be bound to big framework like Spring Boot?

That's really not what I ask. I just ask if it is possible to use a version that is the most compatible with both new and old, instead of blindly using the latest version.

**Also I have not the full picture of Java services at SAP, but I would guess quite a lot are based on Spring Boot 2.x, so I think it is valuable for an SAP library like this one to try to be as compatible as possible with it...**

> * From your point of view, as a library developer, I cannot upgrade **any** dependencies in the future, because I have to make Spring Boot or other framework happy. Therefore, keeping old version will be safe.

I think I already answered this in https://github.com/SAP/btp-environment-variable-access/issues/111#issuecomment-1453761099
I would add again that I would expect libraries to upgrade slower than applications, especially because they should strive supporting as most applications as possible, and not all applications can be expected to upgrade fast.

>   However, keep using old libraries also brings additional risks of vulnerabilities.

For sure we don't ask you to keep a vulnerable library!

> In addition, my scanning tools like blackduck will also tell me, my libraries are outdated.

I guess I am part of the people complaining of that not older than one year rule SAP recently introduced 😄 
So what about that 2017 old jsr305?

> Therefore, as long as application developers can add additional configurations to solve such maven enforce plugin issue (as Alex said, with `exclusion`, runtime has no issues), I dont see better solution.

The whole point of this ticket is to avoid the annoyance on multiple projects consuming this library, and instead handle the problem here.

> * Rolling back to `slf4j` version 1 will be a breaking change.

I cannot see how that's a breaking change, could you explain? Projects consuming this BTP library are not relying on it to set the slf4j-api version. Pretty much the opposite, hence this ticket.


Hi @newtork 

> That's confusing to me: our project does not force your application to use SLF4J API 2.0.6. The opposite is the case here, with 1.7.36 taking precedence.

thee is no precedence here. The error is just about diverging versions, it does not prefer one or the other. It just gives the dev an error so that he can decide which version to use. The rule preference is for the higher version, because the assumption is that a newer version just adds on top of the older one. This is not always true obviously (when we have breaking changes), but is the case here.

> Who has to "be sure"? The developer? The Maven runtime? For me the dependency-tree gives a conflict free dependency resolution.

Sure maven will choose a single version in the end. But it will just take the one closer to the top of the dependency tree, which is not something easy to manage from a dev point of view, and that is quite fragile. Hence why maven enforcer exists in the first place.

> We are arguing on behalf of a 3rd party plugin and rule right now :)

Well, I have seen maven enforcer used in all projects I worked on at SAP at least.

> I'm seeing more risks in rolling back a dependency major version, than benefit. There's a chance we will break something for other projects then.

I don't see the risk, given slf4j-api 2.0 is a super set of 1.7.

> At least, I won't have capacity to facilitate further troubleshooting.

not sure what you mean ?

> I think with your intention the only proper solution with the current releases would be to add an exclusion to the affected dependency, here java-security, i.e. the last option https://github.com/SAP/btp-environment-variable-access/issues/111#issuecomment-1453740142

sure, that's what we are forced to do at the moment in multiple places, hence this ticket 😉 

**I guess another solution would be to add this exclusion in `java-security` pom directly, as https://github.com/SAP/cloud-security-xsuaa-integration chose to remain Spring Boot 2.x compatible. I will create an issue there. (that's a solution for us because we don't use your library directly, but only through `java-security`)**

Thanks
Vivien

**Comment by jjtang1985** [comment]
I have just scanned the long answer (without all the details) and would add more comments:
- This repository (as well as the maven module release) is under Apache licence. There are **no contracts** that limit us to SAP internal user groups. Therefore, we cannot make any assumption about whether our users are using Spring Boot (2). I would say, even for SAP internal, as long as there is not clear evidence, I would not guess this is true or not.
- @newtork , please correct me. I believe, if there are runtime conflicts, our e2e tests should catch it, which is not the case. Therefore, Either there are **no general** `slf4j` version conflict issues at runtime or it's an **edge** case that only happen under additional conditions.
- FYI, the `slf4j` version updates to version 2 happened approx. **7 month** ago.
- `jsr305` has been pointed out as an old lib used in this repository. I would see this is a potential follow up topic. However, it might lead to **confusing** (I hope it's not intended), when the lib `artefactId` only is shown, without telling it's actually under `findbugs`, which is a **compile time static code check tool**. Mixing compile time and runtime risks is not a good idea, from my point of view. In addition, I don't understand the logic of the combination below:
  - I'm not happy with keeping old lib
  - As long as you use one old lib (there is no simply replacement), you should be fine with the second.

Thank you.
Junjie

**Comment by vtintillier** [comment]
> `jsr305` has been pointed out as an old lib used in this repository. I would see this is a potential follow up topic. However, it might lead to **confusing** (I hope it's not intended), when the lib `artefactId` only is shown, without telling it's actually under `findbugs`, which is a **compile time static code check tool**. Mixing compile time and runtime risks is not a good idea, from my point of view. In addition, I don't understand the logic of the combination below:
> * I'm not happy with keeping old lib
> * As long as you use one old lib (there is no simply replacement), you should be fine with the second.

that was just an example that old libs are not always a problem and that this rule should not be bindlly followed...

**Comment by jjtang1985** [comment]
> that was just an example 

Unfortunately, this is a confusing example.  (compile time vs. runtime)

> that old libs are not always a problem and that this rule should not be bindlly followed...

A assume `bindlly` is just a typo and `blindly` is the intended word.
For me, `not always a problem` is just an excuse to avoid actions to reduce the risks of vulnerabilities.
The referenced rule was introduced by SAP or scanning tools. In general, I personally agree with such rule. 
That says, although the dedicated dependency updates were applied by my colleague, I don't agree this is a **blindly decision**.
Perhaps, this [OWASP article](https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/) is a good reading material here.

**Comment by jjtang1985** [comment]
I’m going to close this ticket, as there are no good reasons for that.

> I guess another solution would be to add this exclusion in java-security pom directly, as https://github.com/SAP/cloud-security-xsuaa-integration chose to remain Spring Boot 2.x compatible. I will create an issue there. (that’s a solution for us because we don’t use your library directly, but only through java-security)

As the user did not consume this lib anyways, moving to the security library might be a better idea.
