### ISSUE TITLE
Feat: Decide env variable loading behavior at runtime

### ISSUE THREAD

**Issue by sim-lus** [SAP/btp-environment-variable-access#239]
## Context
We are building a runtime tarball which might be used as a basis in CF and K8S. We don't want to build two different versions for CF (java-sap-vcap-services) and K8S (java-sap-service-operator).

## Request/Suggestion
It would be better to decide which approach should be used at runtime, or at least at deploy time which e.g. an environment variable.

**Comment by newtork** [comment]
Sorry, for asking the naive/obvious question:
Why not just use both dependencies at once?

**Comment by newtork** [comment]
We don't have tests for this specific concern. But for example, the official [XSUAA security authentication and auhorization](https://github.com/SAP/cloud-security-services-integration-library/blob/main/env/pom.xml) library uses this suggested approach.

We developed the library to be lenient with fallbacks: The _service binding accessors_ are statically resolved from Java classpath. If more than one are found, all accessors are tried until a successful result was returned.

_What's the drawback of using both dependencies simultaneously?_

You potentially produce a lot of try-and-error log messages.

We have some users concerned about redundant exception instantiations. This way they can fine-tune their application on dependency-level. Usually this is not concern. though. Just to be clear.

**Comment by sim-lus** [comment]
got it, thanks for the clarification.
